### ISSUE TITLE
[Bug] Certain Triggers cause config to be reset

### ISSUE THREAD

**Issue by WesBosch** [DelvUI/DelvCD#25]
Adding new triggers sometimes causes the caravan to arrive, wiping the user's config in the process. 

Steps to reproduce:
- Make an Icon
- Select AST Job Gauge as a trigger (Specific options don't seem to matter, I selected Card: None in my test)
- Add a second trigger
- Imgui does this until the game is restarted, the DelvCD config file is wiped in the process

Error from log attached, issue seems to stem from UpdateDataSources grabbing a negative value but I can't really figure out much more. No other errors present, reproducable on current release (1.0.0.2) and on previous version (1.0.0.1), Have not tested any releases older than that.

[dalamud.log](https://github.com/DelvUI/DelvCD/files/15367246/dalamud.log)

![image](https://github.com/DelvUI/DelvCD/assets/63926174/03cab1fa-c931-46fa-95f7-bcf747b576fc)
[dalamud.log](https://github.com/DelvUI/DelvCD/files/15367246/dalamud.log)

**Comment by Tischel** [comment]
Fixed in v1.0.1.1
