### ISSUE TITLE
Charge Count for PCT's Living Muse not showing correctly

### ISSUE THREAD

**Issue by vindagor** [DelvUI/DelvCD#33]
Trigger:  Cooldown > PvE  > Living Muse

When setting to show when "Charge Count == 1", when it goes from either 0 to 1 charge or 2 to 1 charges, it takes 20 more seconds before the icon shows up. Same issue with "Charge Count == 2", except the delay is 40 seconds.

**Comment by Tischel** [comment]
Fixed in v1.1.0.1
