### ISSUE TITLE
Essential Dignity cooldown not working correctly

### ISSUE THREAD

**Issue by jas0917** [DelvUI/DelvCD#34]
![image](https://github.com/DelvUI/DelvCD/assets/13126850/19400014-5a08-4792-bb7e-6aa640a586c6)
![image](https://github.com/DelvUI/DelvCD/assets/13126850/90211bf3-ebad-4e57-82d4-227874fd67e5)
![image](https://github.com/DelvUI/DelvCD/assets/13126850/30dc45a8-b657-42f4-9cf3-f9ff32454a1b)

For some reason the cooldown and stacks don't match. I used this same setup prior to update and it did. Can't figure it out.

**Comment by Tischel** [comment]
Fixed in v1.1.0.1
