### ISSUE TITLE
Machinist Drill [cooldown_timer] tag displaying incorrect time

### ISSUE THREAD

**Issue by Themail2** [DelvUI/DelvCD#36]
![image](https://github.com/DelvUI/DelvCD/assets/118008349/41051f5e-f40d-4451-ba14-6cc10d409379)

**Comment by Themail2** [comment]
This is also the case for Bioblaster

**Comment by dmien47** [comment]
Instead of [cooldown_timer] showing cooldown till next stack is available, it shows time until both stacks are available. [cooldown_stacks] also does not work at all for these abilities.

**Comment by Tischel** [comment]
Fixed in v1.1.0.1
