### ISSUE TITLE
Viper JobGauge condition not working?

### ISSUE THREAD

**Issue by steeben** [DelvUI/DelvCD#37]
I have a single trigger set for an icon to appear:

Trigger Type: JobGauge
Job: Viper

Trigger Condition: Anguine Tribute Stacks == 5

Visibility settings: Hide if level <100

When I use reawaken and get my 5 stacks of Anguine Tribute, the icon doesn't appear even though the trigger is to show when I have 5 stacks.

![image](https://github.com/DelvUI/DelvCD/assets/13606697/f8fdee38-2c15-45b9-b48c-a48c2eae0695)

**Comment by Zeffuro** [comment]
I'm unable to replicate the bug and when I make icons with the stacks specifically they work, can you export your aura so I can take a look?

**Comment by steeben** [comment]
The last update to DelvCD seems to have fixed it, it's working for me now.
