### ISSUE TITLE
Drill [cooldown_stacks] Capping at 1, CD Bar Display Bug

### ISSUE THREAD

**Issue by Sehnder** [DelvUI/DelvCD#42]
Expected Behavior:  When a bar tracking cooldownstacks is set to label [cooldown_stacks], a stack count will be shown of 0,1, or 2 as appropriate. When going from 1 to 2 charge and using a bar element, the bar should reflect the CD movement.

Actual Behavior: Once the label hits 1, the bar no longer moves and does not update to a 2 label when 2 stacks are hit. Additionally, using drill while cooling down the second charge results in odd bar behavior that does not appear to reflect appropriate cooldown.

Note: Previously drill was showing an incorrect CD of 40 seconds, but this was fixed in the last release. Just reconfirming that this issue is different from that fixed item, as the cooldown timer appropriately counts using 20 seconds.

**Comment by Zeffuro** [comment]
Can you give an export as an example?
It seems to be working fine on my end other than what it does to the labels when we reach 2/2

https://github.com/DelvUI/DelvCD/assets/4972345/c4216fce-e335-4c65-bb9d-5ee0ee8e2204

Here's an export that I tested with: 

```
7BnbbiI39Fciq1JfJpRbCPCWQLNLm25QyGbbIpSaGTO4MWNke0hotV+2D/tJ/YUeX+bGJUTZXRG1PA3nYp+Lz83mn0+f/0bfqeWcoDbqErbodEvvez8yMiORkqVzLJCHbgy54iEAB2rJSIdHExqi9tpSSyit8HmoL3goiJRdrPCAx8InvSggj6hd3kS7oIQFGUMvWhChbjGLiUTtCWaSwCouqaI8yisxWEpFZqV38YwI6svSLfEVF1XvyBH6gi6wIqClIJd0DHr9CgJKIOI38/3ooQH9i3zxltVysmnV7tqlAtYZbQF/QRnrcMbFdgfaj2XykBW6W63602pVMks99Lv7fjD4j6DkOfbvQ8HjKNiHcuUtymkH6nOZ8odzLgICkpSIIQAsdDOl/n0E0WPj0+Bek/rOt51pHN2TII1eBw8U+FxeCD67ETQMM+MMvQNnoVD7xIF9HAQ0gqyr6pTw+WzOiCKOcx8WN5zFDWdxY81iUwSMOhMcM4XyaJkl+DUOaCxttnjoXcijAQ10rgP0hvGH1G0ayJ141WIGJDTVCrWbDjEn2tcm3jW8H/e0ypVWo9x0TjppNqu1k9qm4EhVrL6mnAPFLvGYsEsq1a56v8LoHVkySDEUOJnhU13GMKV9BnxkEM/qNGucsAt5VBdczDDkDhr6nLOAP0R30uTa6OiHo+EMP96t4tE3ayl9LMDKs8if6iMrWwXPGA1dN+CR6nVN+dI/fyZLEDum4XHEecDIseL8rlp3du2zbVRclFSK0asr81WsGI1IUr0c+Arr8LVub6aI6kKDZ1qO9ivShrgoCkwQyO2KrzD+URkOnw7KJB9Go1xmOOk5gVAdc9KHzxP/Qumu32yaxyxsfl7NzceMXs6XrqS/NB/3nmbu5yHN9pVmBXAEiFsq6Zgyqpa7iv0ap4fO2ANeyrcwLqRDggZ6UX/RL2CgJkn4rKJ7UYfPxjo013m3U7qxWhbwH6aUkT4RE4hzY3dBxBtoNSQa4NjXE15hGaCnBKtpbjbshRG4ek2xBF2Q3WF0XhQ2uSQLaKYbcDqZqwWMy+tW2VZxSNKf+Fg3YTt6dWKp+AxQAyWMUTp7U6Ru91ClRumJZqeTO2YrQpd3IU3Oo0oJgqRUAZ69jwSKQsyvTwQW/TUr1fFp/TASHEaCLx4JDuXy/1suD2f/Xz17N4vv6mtFtnTZ1XzXhaHjGlvyxpQuddp0BTxImlKjvWg7Lth0FvwJBmT+c7usIbSzahmYvyx0pliExL1jpU9fKS5ZmWEKi0EdnpMGUEL20HuJx/oe4qgWzMjXOIIdp8S/T1kMKuO45LJIB0RGTauuvUkk79+5q1HuArXJ9W8Jm0MOl/Js6fEnDu/pR6pGvQVvRD1fy6qV6+CPX/CjfRg0Mo3hmlPHT+GINkxQzxd7elpvJWJPm/WC1PK3klpt1cvwnGmltmqtoljIuK1iK1D/dAX8epf04n8UL+/HiZm6NH0vYbHUV86NJfxfAAAA//8DAA==
```

**Comment by Sehnder** [comment]
Thanks Zeffuro- import worked as expected and I did a recreate from scratch which is also working. Upon further review, it looks like the trigger for one of the temp elements I was using to test the previous drill issue was incorrect. 

Thank you again, closing this out!
